// <auto-generated />
namespace REMAX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class final11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(final11));
        
        string IMigrationMetadata.Id
        {
            get { return "201912202251420_final11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
